language: cpp

sudo: required
dist: trusty

compiler:
  - gcc
  - clang

os:
  - linux
  - osx

matrix:
  exclude:
    - os: osx
      compiler: gcc
    - os: linux
      compiler: clang

before_install:
  - if [ "$TRAVIS_OS_NAME" == "osx" ]; then
    brew update;
    brew install qt5 cmake boost;
    brew install homebrew/science/nixio --HEAD;
    fi

  - if [ "$TRAVIS_OS_NAME" == "linux" ]; then
    sudo apt-get install -qq
    sudo apt-get install -q gcc-4.8 g++-4.8 libstdc++-4.8-dev libboost-all-dev -y;
    sudo apt-get install libcppunit-dev libboost-all-dev libhdf5-serial-dev libhdf5-dev libhdf5-7 -y;
    sudo apt-get install qt5-default qttools5-dev-tools -y;
    g++ --version;
    mkdir nix-build;
    cd nix-build;
    git clone https://github.com/G-Node/nix;
    cd nix;
    mkdir build;
    cd build;
    cmake -DBUILD_TESTING=OFF ..;
    make all;
    sudo make install;
    cd ../../..;
    fi

  
install:
  - if [ "$CXX" == "g++" ]; then 
    export CXX="g++-4.8"; 
    export COMPILER="g++";
    $CXX --version; 
    else 
    clang --version;
    fi

script: 
  - if [  "$TRAVIS_OS_NAME" == "linux" ]; then
    cmake . && make
    fi
  
  - if [ "$TRAVIS_OS_NAME" == "osx" ]; then
    export CMAKE_PREFIX_PATH=/usr/local/Cellar/qt5;
    cmake . && make
    fi
